from django.urls import path
from . import views

urlpatterns = [
    path('', views.home),
    path('lecture0/', views.lecture0),
    path('lecture1/', views.lecture1),
    path('lecture2/', views.lecture2),
    path('lecture3/', views.lecture3),
    path('lecture4/', views.lecture4),
    path('lecture5/', views.lecture5),
    path('lecture6/', views.lecture6),
    path('lecture7/', views.lecture7),
    path('lecture8/', views.lecture8),
    path('lecture9/', views.lecture9),
    path('lecture10/', views.lecture10),
    path('lecture11/', views.lecture11),
    path('lecture12/', views.lecture12),
    path('review1/', views.review1),
    path('lecture14/', views.lecture14),
    path('lecture15/', views.lecture15),
    path('lecture16/', views.lecture16),
    path('lecture17/', views.lecture17),
    path('lecture18/', views.lecture18),
    path('lecture19/', views.lecture19),
    path('lecture20/', views.lecture20),
    path('lecture21/', views.lecture21),
    path('lecture22/', views.lecture22),
    path('lecture23/', views.lecture23),
    path('lecture24/', views.lecture24),
    path('review2/', views.review2),
    path('lecture25/', views.lecture25),
    path('lecture26/', views.lecture26),
    path('lecture27/', views.lecture27),
    path('lecture28/', views.lecture28),
    path('lecture29/', views.lecture29),
    path('lecture30/', views.lecture30),
    path('lecture31/', views.lecture31),
    path('review3/', views.review3),
    path('lecture33/', views.lecture33),
    path('finalreview/', views.finalreview)
]
